# spring mvc
spring:
  application:
    name: demo-application
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  sleuth:
    enabled: true
    log:
      slf4j:
        enabled: true
    sampler:
      probability: 1
    web:
      skipPattern: /actuator/.*
  zipkin:
    enabled: true
    baseUrl: \${zipkin.baseurl}
    service:
      name: itg-composition
    sender:
      type: web
